[metadata]
name = mcaddon
version = attr: mcaddon.__version__
author = Legopitstop
author_email=legopitstop@lpsmods.dev
description=Minecraft: Bedrock Edition development kit
keywords=Minecraft: Bedrock Edition, mcpack, mcaddon, behaviorpack, resourcepack, JSON
url=https://github.com/legopitstop/mcaddon-py/
project_urls=
    Download=https://github.com/legopitstop/mcaddon-py/releases
    Documentation=https://docs.lpsmods.dev/mcaddon/
    Source Code=https://github.com/legopitstop/mcaddon-py
long_description=file: README.md
long_description_content_type=text/markdown
license=MIT
license_file=LICENSE
# Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
classifiers = 
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    
[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.10
install_requires =
    pydantic
    mcpath
    mclang
    molang
    commentjson
    mini-racer
    pillow
    rapidnbt
    watchdog
    Deprecated
    context_menu
    
[options.entry_points]
console_scripts =
    mcaddon = mcaddon.toolchain.cli:main
    
[options.extras_require]
testing=
    pytest>=6.0
    pytest-cov>=2.0
    mypy>=1.11.2
    flake8>=3.9
    tox>=3.24
    types-Deprecated
    types-requests

[options.package_data]
mcaddon = ["py.typed", "assets/**/*"]

[flake8]
max-line-length=160
extend-ignore=F401, F403, E203
